name: format

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    clang-format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: KyleMayes/install-llvm-action@v2
              with:
                  version: "18"
            - run: |
                  git ls-files \
                      | grep -E '\.(c|h)$' | grep -Ev '^include/efi' \
                      | grep -Ev '^include/fonts' \
                      | xargs clang-format --verbose -i
                  git diff --exit-code
