name: kernel

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

defaults:
    run:
        working-directory: kernel

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: KyleMayes/install-llvm-action@v2
              with:
                  version: "18"
            - run: make
